apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ftc-app

bases:
  - ../../base

namePrefix: dev-

commonLabels:
  environment: development

replicas:
  - name: execution-service
    count: 1

configMapGenerator:
  - name: execution-service-config
    behavior: merge
    literals:
      - EVENT_BUS_NAME=fiap-tech-challenge-event-bus

images:
  - name: execution-service
    newName: execution-service
    newTag: dev-latest

patches:
  - target:
      kind: ServiceAccount
      name: execution-service
    patch: |-
      - op: replace
        path: /metadata/annotations/eks.amazonaws.com~1role-arn
        value: arn:aws:iam::305032652600:role/fiap-execution-service-dev
