apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ftc-app-production

bases:
  - ../../base

namePrefix: prod-

commonLabels:
  environment: production

configMapGenerator:
  - name: execution-service-config
    behavior: merge
    literals:
      - EVENT_BUS_NAME=fiap-tech-challenge-events-production
      - DYNAMODB_TABLE_NAME=fiap-tech-challenge-executions-production
      - SQS_QUEUE_URL=https://sqs.us-east-1.amazonaws.com/305032652600/execution-service-events-production

images:
  - name: execution-service
    newName: execution-service
    newTag: prod-latest

patches:
  - target:
      kind: ServiceAccount
      name: execution-service
    patch: |-
      - op: replace
        path: /metadata/annotations/eks.amazonaws.com~1role-arn
        value: arn:aws:iam::305032652600:role/fiap-execution-service-prod
