apiVersion: v1
kind: ConfigMap
metadata:
  name: execution-service-config
data:
  EVENT_BUS_NAME: ""  # Will be set by overlay
  DYNAMODB_TABLE_NAME: ""  # Will be set by overlay
  SQS_QUEUE_URL: ""  # Will be set by overlay
