apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ftc-app

resources:
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - secret.yaml

commonLabels:
  app.kubernetes.io/name: execution-service
  app.kubernetes.io/part-of: fiap-tech-challenge
